version: '2'
services:
    seckill-app:
        image: seckill
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://seckill-mysql:3306/seckill?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8086:8080
    seckill-mysql:
        extends:
            file: mysql.yml
            service: seckill-mysql
